spring.application.name=bloodmanagement
spring.datasource.url=jdbc:mysql://localhost:3306/bloodmanagement
server.port=7999
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=28bd35c78786bb
spring.mail.password=b5db281842d4ae
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# URL of your frontend reset-password page
app.reset-password.base-url=http://localhost:4201/reset-password
# Token expiry in minutes (2 minutes as required)
app.reset-password.expiry-minutes=10